//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atdl4net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HumanReadableTypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanReadableTypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atdl4net.Resources.HumanReadableTypeNames", typeof(HumanReadableTypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * = Mandatory.
        /// </summary>
        public static string AddMandatoryFieldLabel {
            get {
                return ResourceManager.GetString("AddMandatoryFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean value.
        /// </summary>
        public static string BooleanType {
            get {
                return ResourceManager.GetString("BooleanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char value.
        /// </summary>
        public static string CharType {
            get {
                return ResourceManager.GetString("CharType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country code.
        /// </summary>
        public static string CountryType {
            get {
                return ResourceManager.GetString("CountryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency.
        /// </summary>
        public static string CurrencyType {
            get {
                return ResourceManager.GetString("CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data value.
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DateType {
            get {
                return ResourceManager.GetString("DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange code.
        /// </summary>
        public static string ExchangeType {
            get {
                return ResourceManager.GetString("ExchangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string LanguageType {
            get {
                return ResourceManager.GetString("LanguageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month-year value.
        /// </summary>
        public static string MonthYearType {
            get {
                return ResourceManager.GetString("MonthYearType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        public static string NumericType {
            get {
                return ResourceManager.GetString("NumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        public static string StringType {
            get {
                return ResourceManager.GetString("StringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenor value.
        /// </summary>
        public static string TenorType {
            get {
                return ResourceManager.GetString("TenorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date/time.
        /// </summary>
        public static string TimestampType {
            get {
                return ResourceManager.GetString("TimestampType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string TimeType {
            get {
                return ResourceManager.GetString("TimeType", resourceCulture);
            }
        }
    }
}
